<?php
return [
    'Dashboard' => [
        ['label' => 'Dashboard', 'name' => 'dashboard'],
    ],
    'Role' => [
        ['label' => 'Index', 'name' => 'role.index'],
        ['label' => 'Create', 'name' => 'role.create'],
        ['label' => 'Store', 'name' => 'role.store'],
        ['label' => 'Edit', 'name' => 'role.edit'],
        ['label' => 'Update', 'name' => 'role.update'],
        ['label' => 'Delete', 'name' => 'role.destroy'],
    ],
    'User' => [
        ['label' => 'Index', 'name' => 'user.index'],
        ['label' => 'Create', 'name' => 'user.create'],
        ['label' => 'Store', 'name' => 'user.store'],
        ['label' => 'Edit', 'name' => 'user.edit'],
        ['label' => 'Update', 'name' => 'user.update'],
        ['label' => 'Delete', 'name' => 'user.destroy'],
        ['label' => 'Change Password', 'name' => 'user.change-password'],
        ['label' => 'Update Profile', 'name' => 'user.update-profile'],
    ],
    'Customer' => [
        ['label' => 'Index', 'name' => 'customer.index'],
        ['label' => 'Create', 'name' => 'customer.create'],
        ['label' => 'Store', 'name' => 'customer.store'],
        ['label' => 'Edit', 'name' => 'customer.edit'],
        ['label' => 'Update', 'name' => 'customer.update'],
        ['label' => 'Delete', 'name' => 'customer.destroy'],
    ],
    'Supplier' => [
        ['label' => 'Index', 'name' => 'supplier.index'],
        ['label' => 'Create', 'name' => 'supplier.create'],
        ['label' => 'Store', 'name' => 'supplier.store'],
        ['label' => 'Edit', 'name' => 'supplier.edit'],
        ['label' => 'Update', 'name' => 'supplier.update'],
        ['label' => 'Delete', 'name' => 'supplier.destroy'],
    ],
    'Unit' => [
        ['label' => 'Index', 'name' => 'unit.index'],
        ['label' => 'Create', 'name' => 'unit.create'],
        ['label' => 'Store', 'name' => 'unit.store'],
        ['label' => 'Edit', 'name' => 'unit.edit'],
        ['label' => 'Update', 'name' => 'unit.update'],
        ['label' => 'Delete', 'name' => 'unit.destroy'],
    ],
    'Category' => [
        ['label' => 'Index', 'name' => 'category.index'],
        ['label' => 'Create', 'name' => 'category.create'],
        ['label' => 'Store', 'name' => 'category.store'],
        ['label' => 'Edit', 'name' => 'category.edit'],
        ['label' => 'Update', 'name' => 'category.update'],
        ['label' => 'Delete', 'name' => 'category.destroy'],
    ],
    'Medicine' => [
        ['label' => 'Index', 'name' => 'product.index'],
        ['label' => 'Create', 'name' => 'product.create'],
        ['label' => 'Store', 'name' => 'product.store'],
        ['label' => 'Show', 'name' => 'product.show'],
        ['label' => 'Edit', 'name' => 'product.edit'],
        ['label' => 'Update', 'name' => 'product.update'],
        ['label' => 'Delete', 'name' => 'product.destroy'],
    ],
    'Purchase' => [
        ['label' => 'Index', 'name' => 'purchase.index'],
        ['label' => 'Create', 'name' => 'purchase.create'],
        ['label' => 'Store', 'name' => 'purchase.store'],
        ['label' => 'Show', 'name' => 'purchase.show'],
        ['label' => 'Edit', 'name' => 'purchase.edit'],
        ['label' => 'Update', 'name' => 'purchase.update'],
        ['label' => 'Delete', 'name' => 'purchase.destroy'],
        ['label' => 'Invoice', 'name' => 'purchase.invoice'],
    ],
    'Sale' => [
        ['label' => 'Index', 'name' => 'sale.index'],
        ['label' => 'Create', 'name' => 'sale.create'],
        ['label' => 'Store', 'name' => 'sale.store'],
        ['label' => 'Show', 'name' => 'sale.show'],
        ['label' => 'Edit', 'name' => 'sale.edit'],
        ['label' => 'Update', 'name' => 'sale.update'],
        ['label' => 'Delete', 'name' => 'sale.destroy'],
        ['label' => 'Invoice', 'name' => 'sale.invoice'],
    ],
    'Payment Method' => [
        ['label' => 'Index', 'name' => 'gateway.index'],
        ['label' => 'Create', 'name' => 'gateway.create'],
        ['label' => 'Store', 'name' => 'gateway.store'],
        ['label' => 'Edit', 'name' => 'gateway.edit'],
        ['label' => 'Update', 'name' => 'gateway.update'],
        ['label' => 'Delete', 'name' => 'gateway.destroy'],
    ],
    'Prescription' => [
        ['label' => 'Index', 'name' => 'prescription.index'],
        ['label' => 'Create', 'name' => 'prescription.create'],
        ['label' => 'Store', 'name' => 'prescription.store'],
        ['label' => 'Edit', 'name' => 'prescription.edit'],
        ['label' => 'show', 'name' => 'prescription.show'],
        ['label' => 'Update', 'name' => 'prescription.update'],
        ['label' => 'Delete', 'name' => 'prescription.destroy'],
    ],
    'Product Stock' => [
        ['label' => 'Stock', 'name' => 'stock.index'],
        ['label' => 'Low Stock', 'name' => 'report.low_stock'],
        ['label' => 'Stockout', 'name' => 'report.stockout'],
        ['label' => 'Upcoming Expired', 'name' => 'report.upcoming_expire'],
        ['label' => 'Already Expired', 'name' => 'report.already_expire'],
    ],
    'Reports' => [
        ['label' => 'Sale Report', 'name' => 'report.sales'],
        ['label' => 'purchase Report', 'name' => 'report.purchases'],
    ],
    'Setting' => [
        ['label' => 'Show', 'name' => 'settings'],
        ['label' => 'Update', 'name' => 'update.settings'],
    ],
    'Database Backup' => [
        ['label' => 'Index', 'name' => 'database_backup.index'],
        ['label' => 'Create', 'name' => 'database_backup.create'],
    ],
];
